# Generated by Django 3.2 on 2025-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='game1',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='game2',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='game3',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='static/assets/profile_image'),
        ),
    ]
